# Generated by Django 4.2.5 on 2023-10-04 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, upload_to='media/actors', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('date_death', models.DateField(blank=True, verbose_name='Дата смерти')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикация')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актёры',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(blank=True, max_length=150, verbose_name='Описание')),
                ('url', models.SlugField(max_length=100, verbose_name='ссылка')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикация')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Тег')),
                ('premier', models.DateField(default=datetime.date.today, verbose_name='Премьера фильма')),
                ('year', models.DateField(verbose_name='Год')),
                ('poster', models.ImageField(blank=True, upload_to='media/movies', verbose_name='Постер')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('fees', models.CharField(blank=True, max_length=25, verbose_name='Доход')),
                ('budget', models.CharField(blank=True, max_length=25, verbose_name='Бюджет')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='Ссылка')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикация')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='movies.actor', verbose_name='Актёр')),
                ('category', models.ManyToManyField(related_name='category', to='movies.category', verbose_name='Категория')),
                ('country', models.ManyToManyField(blank=True, to='movies.country', verbose_name='Страна')),
                ('directors', models.ManyToManyField(related_name='film_director', to='movies.actor', verbose_name='Режиссёр')),
                ('genre', models.ManyToManyField(related_name='genre', to='movies.category', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Звезда')),
            ],
            options={
                'verbose_name': 'Звезда',
                'verbose_name_plural': 'Звёзды',
            },
        ),
        migrations.CreateModel(
            name='Type_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Фильм, сериал, аниме, мультик и т.д.', max_length=50, verbose_name='Тип произведения')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('text', models.TextField(max_length=5000, verbose_name='Описание')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.review', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25, verbose_name='IP адрес')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.star', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Movie_shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/movie_shot', verbose_name='картинка')),
                ('tag', models.CharField(blank=True, max_length=75, verbose_name='Загаловок')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Кадр к фильму',
                'verbose_name_plural': 'Кадры к фильму',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='type_movie',
            field=models.ForeignKey(default=0, help_text='Фильм, сериал, аниме, мультик и т.д.', on_delete=django.db.models.deletion.SET_DEFAULT, to='movies.type_movie', verbose_name='Тип произведения'),
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.country', verbose_name='Страна'),
        ),
    ]
