# Generated by Django 4.2.5 on 2023-10-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_date_birth_alter_actor_date_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
